volumes:
  db_value:
  static_volume:

services:
  db:
    image: postgres:16.2-alpine
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
      image: redis:alpine3.18
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5

  backend:
    build:
      context: ../.
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static_volume:/app_tools/static/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.25.2-alpine3.18-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles/
    depends_on:
      - backend